### ISSUE TITLE
Exception from kad.py when connection lost

### ISSUE THREAD

**Issue by dakk** [contractvm/contractvmd#11]
```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.4/dist-packages/contractvm-0.6.2.3-py3.4.egg/contractvmd/dht.py", line 107, in serviceThread
    self.dht.bootstrap ()
```

**Comment by dakk** [comment]
Solved 5d7d76a5cca7dd9953b59471738506aa967dc6e8
