### ISSUE TITLE
Backend RPC, message parsing bug

### ISSUE THREAD

**Issue by dakk** [contractvm/contractvmd#14]
[2015-12-14 15:29:50,643] chain: New block found 626240
[2015-12-14 15:29:50,440] chain: Parsing block 2015-12-14 08:34:59 - 626240 0000000000000f500c6b79d3da4b2276bb50217f9ffac3b1c1988f996d8f77ce

Traceback (most recent call last):
  File "/usr/local/bin/contractvmd", line 9, in <module>
    load_entry_point('contractvm==0.6.9.7', 'console_scripts', 'contractvmd')()
  File "/usr/local/lib/python3.5/dist-packages/contractvm-0.6.9.7-py3.5.egg/contractvmd/contractvmd.py", line 317, in main
  File "/usr/local/lib/python3.5/dist-packages/contractvm-0.6.9.7-py3.5.egg/contractvmd/contractvmd.py", line 219, in core
  File "/usr/local/lib/python3.5/dist-packages/contractvm-0.6.9.7-py3.5.egg/contractvmd/chain/chain.py", line 229, in run
  File "/usr/local/lib/python3.5/dist-packages/contractvm-0.6.9.7-py3.5.egg/contractvmd/chain/chain.py", line 111, in parseBlock
  File "/usr/local/lib/python3.5/dist-packages/contractvm-0.6.9.7-py3.5.egg/contractvmd/chain/message.py", line 117, in fromTransaction
  File "/usr/local/lib/python3.5/dist-packages/contractvm-0.6.9.7-py3.5.egg/contractvmd/chain/message.py", line 117, in <genexpr>
ValueError: invalid literal for int() with base 16: 'OP'

**Comment by dakk** [comment]
33690a5516a024e718e75375c802b138929cfe46
